language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "syhan"
  - git config user.email "syhannnn@gmail.com"
  - git add .
  - git commit -m "site updated"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
  global:
    - GH_REF: github.com/syhan/syhan.github.com.git
    - GH_TOKEN: 66eb019ce2da079eda3d9c8ef1d49cf11579d586